'use strict';

 /**
 * user controller file * autogenerated by mongoose-scaffold-crud **/

var users = require('express').Router(),
    Model = require('../models/model-users.js');

var md5 = require('md5');
var jwt = require('jsonwebtoken');
var jwtSecret = 'xxxx';


users.post('/login', function(req, res) {
    // var username = req.params.username;
    // var password = req.params.password;
    var username = 'Admin';
    var password = 'admin';
    var encrypted_password = md5(password);
    // console.log(encrypted_password);
    Model.findOne({username: username, encrypted_password: encrypted_password}, function(err, user){
        if (req.accepts('html', 'json') === 'json') {
            if(err) {
                return res.json(500, {
                    message: 'Error getting user.'
                });
            }
            if(!user) {
                return res.json(404, {
                    message: 'No such user.'
                });
            }
            return res.json(user);
        } else {
            if(err) {
                return res.send('500: Internal Server Error', 500);
            }
            if(!user) {
                return res.end('No such user');
            }
            //Found user

            var token = jwt.sign(user, jwtSecret, { expiresIn: 5 });
            res.json({token: token});
        }
    });
});

module.exports = users;