'use strict';

 /**
 * user controller file * autogenerated by mongoose-scaffold-crud **/

var users = require('express').Router(),
    Model = require('../models/model-users.js');

var md5 = require('md5');
var jwt = require('jsonwebtoken');
var jwtSecret = 'xxxx';


users.post('/login', function(req, res) {
    var username = req.body.username;
    var password = req.body.password;
    var encrypted_password = md5(password);
    Model.findOne({username: username}, function(err, user){
        if(err) {
            return res.send('500: Internal Server Error', 500);
        }
        if(!user) {
            return res.end('No such user');
        }
        //Found user

        var token = jwt.sign(user, jwtSecret, { expiresIn: 5 });
        var response = {token: token};
        res.json(response);
    });
});

module.exports = users;