'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

/**
 * team model file
 * autogenerated by mongoose-scaffold-crud
 */

var teamsSchema = new Schema({
    name: 'String'
});

module.exports = mongoose.model('teams', teamsSchema);