'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

/**
 * match model file
 * autogenerated by mongoose-scaffold-crud
 */
var roomsSchema = new Schema({
    name    : 'String', 
    number_of_fans   : 'Number'
});


var matchesSchema = new Schema({
    due_date: 'String',
    team_one: 'String',
    team_one_score: 'String',
    team_one_avatar_url: 'String',
    team_two: 'String',
    team_two_score: 'String',
    team_two_avatar_url: 'String',
    rooms: [roomsSchema]
});

module.exports = mongoose.model('matches', matchesSchema);