'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

/**
 * user model file
 * autogenerated by mongoose-scaffold-crud
 */

var usersSchema = new Schema({
    username: 'String',
    encrypted_password: 'String'
});

module.exports = mongoose.model('users', usersSchema);